FROM node:19-bullseye-slim

WORKDIR /app

RUN \
    adduser --disabled-login nopriv \
    && chown -R nopriv /app

COPY package.json package-lock.json tsconfig.json ./
RUN npm install

COPY src/ /app/src/
COPY public/ /app/public/

EXPOSE 3000
ENV PORT=3000

CMD ["npm", "run", "start"]
