FROM node:19-bullseye-slim

WORKDIR /app
# RUN adduser --disabled-login nopriv \
#     && chown nopriv:nopriv /app
# COPY --chown=nopriv:nopriv 
# USER nopriv

COPY ./package*.json tsconfig.json ./
RUN npm install

COPY src/ ./src/
COPY public/ ./public/

EXPOSE 3000
ENV PORT=3000

CMD [ \
    "bash", "-c", \
    "npm start"\
]
